# Site configuration
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pawelgrzybek.com" # the base hostname & protocol for your site
permalink: /:title/

# Theme specific configuration
title: pawelgrzybek.com
description: >
  Hi there, I'm Pawel Grzybek, Front-end Developer from Poland.
  Nowadays I live in Northampton (UK). When I'm not coding,
  I'm spinning funky vinyl records.
# Contact and social media links
twitter_username: pawelgrzybek
github_username: pawelgrzybek
facebook_username: grzybecki
instagram_username: pawelgrzybek
linkedin_username: pgrzybek

exclude: ['node_modules', 'gulpfile.js', 'package.json']

# defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

kramdown:
  input: GFM

gems: ['jekyll-paginate']

# Pagination
paginate: 10
paginate_path: /page:num
